name: HACS Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate HACS plugin structure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show repo structure (debug)
        run: tree -a -I '.git'

      - name: Run HACS validation (plugin)
        run: |
          docker run --rm -v "${{ github.workspace }}:/data" hacs/validate:latest
