name: HACS Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hacs-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug repo structure
        run: |
          echo "=== Tree structure ==="
          tree -a -I '.git'
          echo "=== hacs.json ==="
          cat hacs.json || echo "❌ hacs.json not found"

      - name: Run HACS validation (plugin)
        run: |
          docker run --rm -v "${{ github.workspace }}:/data" ghcr.io/hacs/integration:latest
